### PR TITLE
startOf function is accepting number as weekday from 0(Sun) to 6(Sat)

### LINKED ISSUE #22: Fix startOf function for isoWeek
The startOf function is accepting a boolean for Sunday(false) and Monday(true).

Instead it should get the the week day (number) between 0 (Sunday) and 6(Saturday) in order to be more flexible to provide the startOf the week based on the parameter.

See https://github.com/chartjs/chartjs-adapter-luxon/issues/23

### PR DESCRIPTION
**Pull request by stockiNail**
Fixes #22

### CODE REVIEW

**Review by etimberg — APPROVED** [review]

**Review by kurkle — COMMENTED** [review]
I think the throw from `date-fns` should be sufficient:
https://github.com/date-fns/date-fns/blob/7399f7c196d1df9369ef015c5bc17fbff0535da5/src/startOfWeek/index.js#L51-L53

**Comment by stockiNail** [comment]
> 
> 
> I think the throw from `date-fns` should be sufficient:
> https://github.com/date-fns/date-fns/blob/7399f7c196d1df9369ef015c5bc17fbff0535da5/src/startOfWeek/index.js#L51-L53

I have seen it. Do you think it's better to remove the normalization of weekday var?

**Comment by kurkle** [comment]
> I have seen it. Do you think it's better to remove the normalization of weekday var?

I think its not needed. Having 3 additional function calls for every date value can cost a little bit of time in a large dataset.
Also normalizing hides the configuration error rather than throwing it to the user.
`+` casts it to number, (and false=0, true=1), so I'm not sure anything needs to be done.

**Comment by stockiNail** [comment]
Ok for me! Therefore this pull request is not needed, Maybe you can refuse it.

**Comment by stockiNail** [comment]
commited with `+weekday`

**Pull request closed without merging**
